### ISSUE TITLE
About the routing biases

### ISSUE THREAD

**Issue by ChristofferM** [naturomics/CapsNet-Tensorflow#77]
In 5b4eb1a biases for s_j were added. How is this motivated? It is not in the NIPS-paper?
Also shouldn't B_IJ be learned?

**Comment by naturomics** [comment]
The paper didn't mention this.  The biases term is motivated by the fact that capsule is essentially an extend of neuron from two aspect: 1. the separation of coupling assignment c from weight w; 2. matrix representation of x_i instead of scalar
<img src="http://www.sciweavers.org/tex2img.php?eq=%24y_j%3Df%5Cbig%28%5Csum_i%28c_%7Bij%7Dw_%7Bij%7D%29x_i%2Bb_j%5Cbig%29%3Df%28%5Csum_i%20%5Ctilde%7Bw%7D_%7Bij%7Dx_i%2Bb_j%29%24&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0" align="center" border="0" alt="$y_j=f\big(\sum_i(c_{ij}w_{ij})x_i+b_j\big)=f(\sum_i \tilde{w}_{ij}x_i+b_j)$" width="335" height="22" />
the coupling assignment c is learned by routing algorithm, and w by back-propagation. It's not mentioned in paper, but similar to neuron, a bias term for intercept would be more reasonable. For a more intuitive comparison of capsule and neuron, see the [picture](https://github.com/naturomics/CapsNet-Tensorflow/raw/master/imgs/capsuleVSneuron.png) in readme. We will soon publish our work discussing the relation of capsule and neuron in more detail, welcome to follow

**Comment by ChristofferM** [comment]
Thanks! Looking forward to it.
